### ISSUE TITLE
Fix for using on a secure page, or if using jQuery.noConflict

### ISSUE THREAD

**Issue by brentkelly** [miloss/jquery-geolocation-edit#3]
Hi guys,

Great plugin. A couple of small fixes to make the code a bit more robust:

  * Currently doesn't support using the script on a https:// encoded page. Throws a security error for trying to load a (hardcoded) insecure script
  * Doesn't support jQuery.noConflict() being used (callback code assumes $ will be bound to jQuery)

Have implemented & tested the following fix to line 225 of ``jquery.geolocation.edit.js``:

```javascript
script.src = ( window.location.protocol == 'https:' ? 'https' : 'http' ) + '://maps.googleapis.com/maps/api/js?sensor=false&callback=jQuery.fn.geolocateGMapsLoaded';
```

Fix is to detect https, and also to use ``jQuery`` for the callback instead of ``$``

Cheers!

**Comment by miloss** [comment]
Merged and fixed. Thank you.
